### ISSUE TITLE
Cannot understand the means of result

### ISSUE THREAD

**Issue by houruiyan** [snap-stanford/SATURN#12]
Dear Dr ,

Can you explain the output of saturn ? Finally , I can get a h5ad file which has 256 genes. But I cannot understand the mean of those genes. It also did not contain the name of gene. The cell also did not include the barcode of cell. 

Now, I can get the macrogene and the original genes of four species. Then how can I pearson's correlation for those genes? By using the original data? But it contains different numbers cells. 

For example, here I want to get the expression correlation of pig_GNLY and human_SFTPB, how can I do  it?

![image](https://user-images.githubusercontent.com/56068158/231440443-85cb1ff9-47af-45f5-a793-b867570bdf3b.png)

**Comment by Yanay1** [comment]
You can get the macrogene expression values using the `.obsm["macrogenes"]` slot of the anndata object.

To get the barcodes-- the cells in the SATURN output are in the same order as the anndatas they come from, so you can load those individually and then compare. 

If you want to use the original gene expression values, you have to do that one species at a time, because the genes are not present in each species. That is, you can take the SATURN embeddings and/or macrogene expression results from one species, and add that to the original anndata for the species that has its gene expression.

For the question about correlation-- you can't correlate expression values of genes from different species because there's no cells that will have genes from two species. The expression values that all the cells will have in common are the macrogene expression values. 

The macrogene weights (the image you included) let you interpret the biological meaning of a macrogene-- for the one you linked, it seems they seem to be "saposin-like" proteins https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1175101/ https://maayanlab.cloud/Harmonizome/gene_set/Saposin-like/InterPro+Predicted+Protein+Domain+Annotations

**Comment by houruiyan** [comment]
Thank you for your kind explanation!
