### ISSUE TITLE
Are the classes (OrthologPretrainModel, OrthologMetricModel) used to generate any data?, what is the use of the embeddings generated by SATURNMetricModel class? 

### ISSUE THREAD

**Issue by MohammedZidane** [snap-stanford/SATURN#15]
Hi,
I am going through the code to integrate it with a method used in our lab and I have two questions:

1) I ran Train Saturn notebook and think OrthologPretrainModel, OrthologMetricModel classes are not used at all, why they are there?

2) What I got is that the SATURNPretrainModel class is used to optimize the model to reconstruct the protein embeddings similarities but I do not understand what the SATURNMetricModel does i.e., it does not have a decoder part, what kind of learning happening here and for what?

Thanks!

**Comment by Yanay1** [comment]
Those classes are used for comparing SATURN results to models that use orthologs instead of macrogenes.

The pretrain model is used during pretraining of the autoencoder. Then we switch to just using the encoder part of the autoencoder for metric learning (the metric learning model), and freeze the gene to macrogene weights.

**Comment by MohammedZidane** [comment]
Got it!
Thanks :)
