### ISSUE TITLE
species one hot encoding is the same for frog and zebrafish, shouldn't it be different?

### ISSUE THREAD

**Issue by MohammedZidane** [snap-stanford/SATURN#16]
Hi,
I printed this 
spec_1h[:, spec_idx] = 1.
in the forward function 'SATURNPretrainModel' in the saturn_model.py and got the same one hot encoding for both frog and zebrafish.

species: zebrafish
spec_idx: 0
spec_1h: tensor([[1., 0.],
        [1., 0.],
        [1., 0.],
        ...,
        [1., 0.],
        [1., 0.],
        [1., 0.]], device='cuda:0')

species: frog
spec_idx: 0
spec_1h: tensor([[1., 0.],
        [1., 0.],
        [1., 0.],
        ...,
        [1., 0.],
        [1., 0.],
        [1., 0.]], device='cuda:0')

Shouldn't the one hot encoding be different?
Thanks!

**Comment by Yanay1** [comment]
Thanks so much for finding this error!

Following benchmarking of the method with and without the conditional species variable, it appears the conditional variable degrades performance. For now, I set this variable to constant in the code explicitly here: https://github.com/snap-stanford/SATURN/commit/067d7424f1c25b5e5f0886d1b9545e802d0b21a1#diff-78876826c742197ca1d3e5c76f4c91a4142d850195d9f73504c5e15ccdd43d6dR136 but I included the fix for it in the commented out previous line.
